 .../PATCH.md                                       |  40 [32m+++[m
 .../TESTS.md                                       |  37 [32m+++[m
 .../TODO.md                                        |   9 [32m+[m
 .../PATCH.md                                       |  21 [32m++[m
 .../TESTS.md                                       |  16 [32m++[m
 .../TODO.md                                        |   5 [32m+[m
 .../PATCH.md                                       |  21 [32m++[m
 .../TESTS.md                                       |  15 [32m++[m
 .../TODO.md                                        |   4 [32m+[m
 .../PATCH.md                                       |  15 [32m++[m
 .../TESTS.md                                       |  14 [32m+[m
 .../TODO.md                                        |   4 [32m+[m
 .../PATCH.md                                       |  13 [32m+[m
 .../TESTS.md                                       |  16 [32m++[m
 .../TODO.md                                        |   4 [32m+[m
 .../PATCH.md                                       |  19 [32m++[m
 .../TESTS.md                                       |  18 [32m++[m
 .../TODO.md                                        |   4 [32m+[m
 .../Controller/AbstractRefBookController.php       |  21 [32m+[m[31m-[m
 .../reference/Controller/HomeController.php        |  13 [32m+[m
 .../reference/Controller/PageController.php        |  12 [32m+[m
 .../Controller/ReferenceDiscoveryController.php    |  49 [32m++++[m
 .../Service/ReferenceDiagramModelBuilder.php       |   2 [32m+[m[31m-[m
 .../Service/ReferencePublicSiteService.php         | 280 [32m++++++++++++++++++++[m
 application/reference/templates/layout.twig        |  55 [32m+++[m[31m-[m
 application/reference/templates/pages/legal.twig   |  46 [32m++++[m
 public/assets/css/refbook-runtime.css              | 292 [32m+++++++++++++++++++++[m
 sites/opus-reference/routes.xml                    |   9 [32m+[m
 ...book_header_branding_fine_tune_static_smoke.php |  36 [32m+++[m
 ...eader_branding_pro_readability_static_smoke.php |  35 [32m+++[m
 ...iagram_terminal_labels_english_static_smoke.php |  28 [32m++[m
 ...book_public_seo_branding_final_static_smoke.php |  22 [32m++[m
 ...e_aware_header_language_select_static_smoke.php |  32 [32m+++[m
 ...k_public_visibility_seo_branding_live_smoke.php |  80 [32m++++++[m
 ...public_visibility_seo_branding_static_smoke.php |  99 [32m+++++++[m
 ...book_header_branding_fine_tune_static_smoke.cmd |   2 [32m+[m
 ...eader_branding_pro_readability_static_smoke.cmd |   2 [32m+[m
 ...iagram_terminal_labels_english_static_smoke.cmd |   2 [32m+[m
 ...book_public_seo_branding_final_static_smoke.cmd |   3 [32m+[m
 ...e_aware_header_language_select_static_smoke.cmd |   2 [32m+[m
 ...k_public_visibility_seo_branding_live_smoke.cmd |   3 [32m+[m
 ...public_visibility_seo_branding_static_smoke.cmd |   3 [32m+[m
 42 files changed, 1389 insertions(+), 14 deletions(-)
